// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv9zEHixWBMg5G1zfruYo9bSxDJhKiiRw',
    appId: '1:468203088744:web:b48fc98cf5f911f774c4dd',
    messagingSenderId: '468203088744',
    projectId: 'placementapp-cf5dc',
    authDomain: 'placementapp-cf5dc.firebaseapp.com',
    databaseURL: 'https://placementapp-cf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'placementapp-cf5dc.firebasestorage.app',
    measurementId: 'G-XCRMH30EV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8WC-eM7QkD_wjnlozE8_L9skJBoenPv0',
    appId: '1:468203088744:android:4873bb140389e5dc74c4dd',
    messagingSenderId: '468203088744',
    projectId: 'placementapp-cf5dc',
    databaseURL: 'https://placementapp-cf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'placementapp-cf5dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UMqH72ghYcHhgxIlyDzfgvjvkXAx5tI',
    appId: '1:468203088744:ios:c1aa6416a5021af274c4dd',
    messagingSenderId: '468203088744',
    projectId: 'placementapp-cf5dc',
    databaseURL: 'https://placementapp-cf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'placementapp-cf5dc.firebasestorage.app',
    iosBundleId: 'com.example.place',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1UMqH72ghYcHhgxIlyDzfgvjvkXAx5tI',
    appId: '1:468203088744:ios:c1aa6416a5021af274c4dd',
    messagingSenderId: '468203088744',
    projectId: 'placementapp-cf5dc',
    databaseURL: 'https://placementapp-cf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'placementapp-cf5dc.firebasestorage.app',
    iosBundleId: 'com.example.place',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv9zEHixWBMg5G1zfruYo9bSxDJhKiiRw',
    appId: '1:468203088744:web:470887aee1fc19a974c4dd',
    messagingSenderId: '468203088744',
    projectId: 'placementapp-cf5dc',
    authDomain: 'placementapp-cf5dc.firebaseapp.com',
    databaseURL: 'https://placementapp-cf5dc-default-rtdb.firebaseio.com',
    storageBucket: 'placementapp-cf5dc.firebasestorage.app',
    measurementId: 'G-3HBR3ML371',
  );
}
