import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:place/firebase_options.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:place/screen/login_screen.dart';

// If you have a firebase_options.dart file generated by the FlutterFire CLI, import it here:
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase.
  await Firebase.initializeApp(
    // Uncomment and update the following if you are using firebase_options.dart:
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Supabase.
  await Supabase.initialize(
    url: 'https://fcjdpmcaifpooqgtrmom.supabase.co',
    anonKey:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjamRwbWNhaWZwb29xZ3RybW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1Njk2OTUsImV4cCI6MjA1NDE0NTY5NX0.JEq6JAIJQgJyiV0AhdqrlHXeq35oT8_WTZCMsfDclsg',
  );

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final ValueNotifier<bool> isDarkMode = ValueNotifier(false);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<bool>(
      valueListenable: isDarkMode,
      builder: (context, darkMode, child) {
        return MaterialApp(
          title: 'Placement App',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            brightness: Brightness.light,
            primarySwatch: Colors.blueGrey,
            scaffoldBackgroundColor: Colors.grey[100],
            appBarTheme: AppBarTheme(
              backgroundColor: Colors.white,
              elevation: 0,
              iconTheme: IconThemeData(color: Colors.blueGrey),
              titleTextStyle: TextStyle(
                color: Colors.blueGrey,
                fontSize: 20,
                fontWeight: FontWeight.bold,
              ),
              centerTitle: true,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.vertical(
                  bottom: Radius.circular(20),
                ),
              ),
            ),
          ),
          darkTheme: ThemeData(
            brightness: Brightness.dark,
            primarySwatch: Colors.blueGrey,
            scaffoldBackgroundColor: Colors.black,
            appBarTheme: AppBarTheme(
              backgroundColor: Colors.black,
              elevation: 0,
              iconTheme: IconThemeData(color: Colors.white),
              titleTextStyle: TextStyle(
                color: Colors.white,
                fontSize: 20,
                fontWeight: FontWeight.bold,
              ),
              centerTitle: true,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.vertical(
                  bottom: Radius.circular(20),
                ),
              ),
            ),
          ),
          themeMode: darkMode ? ThemeMode.dark : ThemeMode.light,
          home: LoginScreen(themeNotifier: isDarkMode),
        );
      },
    );
  }
}
